[project]
name = "pyside-config"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.7.3",
    "attrs>=24.2.0",
    "pyside-widgets",
    "loguru>=0.7.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py312"
show-fixes = true
output-format = "concise"
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint]
ignore = ["E501"]
select = ["E", "F", "B"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.pyright]
pythonVersion = "3.12"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownLambdaType = false
typeCheckingMode = "strict"

[tool.uv]
dev-dependencies = [
    "rich>=13.9.2",
    "ipython>=8.28.0",
    "ruff>=0.6.9",
]

[tool.uv.sources]
pyside-widgets = { git = "https://github.com/fred-kr/pyside-widgets.git" }
